`define INPUT_FILE "/mnt/castor/seas_home/b/brentano/cis501/lab4-pipeline/test_data/wireframe.ctrace"
`define OUTPUT_FILE "/mnt/castor/seas_home/b/brentano/cis501/lab4-pipeline/test_data/wireframe.output"
`define ORIG_INPUT_FILE "/mnt/castor/seas_home/b/brentano/cis501/lab4-pipeline/test_data/wireframe.trace"
`define MEMORY_IMAGE_FILE "/mnt/castor/seas_home/b/brentano/cis501/lab4-pipeline/test_data/wireframe.hex"
`define TEST_CASE "wireframe"
